"""
Base SQLAlchemy model and shared column mixins.

Column types follow the database design: UUID primary keys generated by
Postgres, `timestamptz` throughout, and `numeric(12,2)` for money.
"""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, declarative_base, mapped_column

Base = declarative_base()


class UUIDPrimaryKeyMixin:
    """Adds a Postgres-generated UUID primary key."""

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        # Generated server-side so an INSERT that bypasses the ORM still gets one.
        server_default=text("gen_random_uuid()"),
        default=uuid.uuid4,
    )


class CreatedAtMixin:
    """Adds a server-defaulted creation timestamp."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )


class TimestampMixin(CreatedAtMixin):
    """
    Adds creation and update timestamps.

    `updated_at` is maintained by SQLAlchemy on ORM updates. Writes that bypass
    the ORM will not advance it; add a Postgres trigger if that becomes a
    requirement.
    """

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class SerializerMixin:
    """Convenience conversion helpers shared by all models."""

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the instance to a plain dictionary.

        Returns:
            Column names mapped to their current values.
        """
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}

    def __repr__(self) -> str:
        """Return a short identifying representation."""
        identifier = getattr(self, "id", None)
        return f"<{self.__class__.__name__} id={identifier}>"


class BaseModel(Base, UUIDPrimaryKeyMixin, TimestampMixin, SerializerMixin):
    """Base for entities carrying an id plus both timestamps."""

    __abstract__ = True
