"""initial claims schema

Revision ID: 6d674d8aaf69
Revises: None
Create Date: 2026-08-17 11:24:30.953001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d674d8aaf69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('claim_number', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('vehicle_make', sa.String(length=100), nullable=False),
    sa.Column('vehicle_model', sa.String(length=100), nullable=False),
    sa.Column('vehicle_year', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('incident_time', sa.Time(), nullable=True),
    sa.Column('incident_location', sa.String(length=500), nullable=True),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('incident_description', sa.Text(), nullable=False),
    sa.Column('damaged_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity_slider', sa.Integer(), nullable=True),
    sa.Column('damage_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='SUBMITTED', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('SUBMITTED', 'PROCESSING', 'PENDING_REVIEW', 'INFORMATION_REQUIRED', 'INVESTIGATION', 'APPROVED', 'COMPLETED')", name='valid_status'),
    sa.CheckConstraint('severity_slider IS NULL OR (severity_slider BETWEEN 0 AND 5)', name='valid_severity_slider'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number')
    )
    op.create_index('idx_claims_created_at', 'claims', ['created_at'], unique=False)
    op.create_index('idx_claims_created_by_user_id', 'claims', ['created_by_user_id'], unique=False)
    op.create_index('idx_claims_customer_email', 'claims', ['email'], unique=False)
    op.create_index('idx_claims_policy_number', 'claims', ['policy_number'], unique=False)
    op.create_index('idx_claims_status', 'claims', ['status'], unique=False)
    op.create_table('assessments',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('extracted_incident_type', sa.String(length=50), nullable=True),
    sa.Column('extracted_collision_type', sa.String(length=50), nullable=True),
    sa.Column('incident_summary', sa.Text(), nullable=True),
    sa.Column('total_estimated_repair_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('damage_confidence', sa.Integer(), nullable=True),
    sa.Column('policy_status', sa.String(length=50), nullable=True),
    sa.Column('coverage_assessment', sa.String(length=50), nullable=True),
    sa.Column('coverage_reasoning', sa.Text(), nullable=True),
    sa.Column('coverage_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fraud_risk_level', sa.String(length=50), nullable=True),
    sa.Column('fraud_risk_score', sa.Integer(), nullable=True),
    sa.Column('claim_priority', sa.String(length=50), nullable=True),
    sa.Column('priority_reasoning', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(length=100), nullable=True),
    sa.Column('final_summary', sa.Text(), nullable=True),
    sa.Column('overall_confidence', sa.Integer(), nullable=True),
    sa.Column('assessment_status', sa.String(length=50), server_default='PENDING', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("assessment_status IN ('PENDING', 'COMPLETE', 'FAILED')", name='valid_assessment_status'),
    sa.CheckConstraint("claim_priority IS NULL OR claim_priority IN ('FAST_TRACK', 'STANDARD_REVIEW', 'INVESTIGATION')", name='valid_claim_priority'),
    sa.CheckConstraint("fraud_risk_level IS NULL OR fraud_risk_level IN ('LOW', 'MEDIUM', 'HIGH')", name='valid_fraud_risk_level'),
    sa.CheckConstraint('damage_confidence IS NULL OR damage_confidence BETWEEN 0 AND 100', name='valid_damage_confidence'),
    sa.CheckConstraint('fraud_risk_score IS NULL OR fraud_risk_score BETWEEN 0 AND 100', name='valid_fraud_risk_score'),
    sa.CheckConstraint('overall_confidence IS NULL OR overall_confidence BETWEEN 0 AND 100', name='valid_overall_confidence'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessments_claim_id', 'assessments', ['claim_id'], unique=False)
    op.create_index('idx_assessments_claim_priority', 'assessments', ['claim_priority'], unique=False)
    op.create_index('idx_assessments_fraud_risk_level', 'assessments', ['fraud_risk_level'], unique=False)
    op.create_table('documents',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_status', sa.String(length=50), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IS NULL OR document_type IN ('Policy', 'Accident Report', 'Repair Estimate', 'Other')", name='valid_document_type'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_claim_id', 'documents', ['claim_id'], unique=False)
    op.create_table('human_decisions',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=False),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('decision_comments', sa.Text(), nullable=True),
    sa.Column('requested_information', sa.Text(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVED', 'REQUESTED_INFO', 'ESCALATED')", name='valid_decision'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_human_decisions_claim_id', 'human_decisions', ['claim_id'], unique=False)
    op.create_index('idx_human_decisions_created_at', 'human_decisions', ['created_at'], unique=False)
    op.create_table('images',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('analyzed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('analysis_status', sa.String(length=50), nullable=True),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_images_analyzed', 'images', ['analyzed'], unique=False)
    op.create_index('idx_images_claim_id', 'images', ['claim_id'], unique=False)
    op.create_table('damage_items',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('part_name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('estimated_repair_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('repair_cost_reasoning', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_damage_items_assessment_id', 'damage_items', ['assessment_id'], unique=False)
    op.create_table('fraud_indicators',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('indicator_name', sa.String(length=255), nullable=False),
    sa.Column('indicator_category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fraud_indicators_assessment_id', 'fraud_indicators', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fraud_indicators_assessment_id', table_name='fraud_indicators')
    op.drop_table('fraud_indicators')
    op.drop_index('idx_damage_items_assessment_id', table_name='damage_items')
    op.drop_table('damage_items')
    op.drop_index('idx_images_claim_id', table_name='images')
    op.drop_index('idx_images_analyzed', table_name='images')
    op.drop_table('images')
    op.drop_index('idx_human_decisions_created_at', table_name='human_decisions')
    op.drop_index('idx_human_decisions_claim_id', table_name='human_decisions')
    op.drop_table('human_decisions')
    op.drop_index('idx_documents_claim_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_assessments_fraud_risk_level', table_name='assessments')
    op.drop_index('idx_assessments_claim_priority', table_name='assessments')
    op.drop_index('idx_assessments_claim_id', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index('idx_claims_status', table_name='claims')
    op.drop_index('idx_claims_policy_number', table_name='claims')
    op.drop_index('idx_claims_customer_email', table_name='claims')
    op.drop_index('idx_claims_created_by_user_id', table_name='claims')
    op.drop_index('idx_claims_created_at', table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
